### ISSUE TITLE
BUG: SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by Integral-Tech** [Mahdi-zarei/nekoray#323]
## Describe the problem

Expected behavior: nekoray launches successfully

Actual behavior: nekoray fails with SIGSEGV (Address boundary error)

## How to reproduce

- Build nekoray from `dev` branch using PKGBUILD [here](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/nekoray-git/PKGBUILD)
- Install the built package (`nekoray-git`)
- Launch nekoray

```
server name:  "nekoray-P4EpbzSY9vrh709tdgO0fg"
fish: Job 1, 'nekoray' terminated by signal SIGSEGV (Address boundary error)
```

On the contrary, when building nekoray from 4.2.12 source archive using PKGBUILD [here](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/nekoray/PKGBUILD), it launches successfully.

In addition, reverting commit 9f89e48733b651888192409e22afe3f921544c68 can solve this problem.

## log

If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.

```
           PID: 167441 (nekoray)
           UID: 1000 (integral)
           GID: 1000 (integral)
        Signal: 11 (SEGV)
     Timestamp: Sun 2025-03-23 23:29:25 CST (2min 9s ago)
  Command Line: /usr/lib/nekoray/nekoray -appdata
    Executable: /usr/lib/nekoray/nekoray
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.kde.konsole@8dcf21fbd8ff4d959d6f87ce4292bb43.service
          Unit: user@1000.service
     User Unit: app-org.kde.konsole@8dcf21fbd8ff4d959d6f87ce4292bb43.service
         Slice: user-1000.slice
     Owner UID: 1000 (integral)
       Boot ID: ec0d30e2dc484ca88eac015f8c31cb81
    Machine ID: 9198c1294915462dbd97a59ed65ea921
      Hostname: IntegralPC
       Storage: /var/lib/systemd/coredump/core.nekoray.1000.ec0d30e2dc484ca88eac015f8c31cb81.167441.1742743765000000.zst (present)
  Size on Disk: 3.5M
       Message: Process 167441 (nekoray) of user 1000 dumped core.
                
                Stack trace of thread 167441:
                #0  0x00005ece925d7316 n/a (/usr/lib/nekoray/nekoray + 0x88316)
                #1  0x00005ece9264bb37 n/a (/usr/lib/nekoray/nekoray + 0xfcb37)
                #2  0x00005ece9264c19d n/a (/usr/lib/nekoray/nekoray + 0xfd19d)
                #3  0x00005ece926da17d n/a (/usr/lib/nekoray/nekoray + 0x18b17d)
                #4  0x00005ece925b1bac n/a (/usr/lib/nekoray/nekoray + 0x62bac)
                #5  0x00007138cea35488 n/a (libc.so.6 + 0x27488)
                #6  0x00007138cea3554c __libc_start_main (libc.so.6 + 0x2754c)
                #7  0x00005ece925cc085 n/a (/usr/lib/nekoray/nekoray + 0x7d085)
                
                Stack trace of thread 167442:
                #0  0x00007138ceaabbe2 n/a (libc.so.6 + 0x9dbe2)
                #1  0x00007138cea9fe33 n/a (libc.so.6 + 0x91e33)
                #2  0x00007138cea9fe74 n/a (libc.so.6 + 0x91e74)
                #3  0x00007138ceb1aa06 ppoll (libc.so.6 + 0x10ca06)
                #4  0x00007138ce28de27 n/a (libglib-2.0.so.0 + 0xc1e27)
                #5  0x00007138ce229535 g_main_context_iteration (libglib-2.0.so.0 + 0x5d535)
                #6  0x00007138cf3c575d _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x3c575d)
                #7  0x00007138cf1606a6 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x1606a6)
                #8  0x00007138cf257829 _ZN7QThread4execEv (libQt6Core.so.6 + 0x257829)
                #9  0x00007138ce13f6ae n/a (libQt6DBus.so.6 + 0x2e6ae)
                #10 0x00007138cf2d8a9b n/a (libQt6Core.so.6 + 0x2d8a9b)
                #11 0x00007138ceaa370a n/a (libc.so.6 + 0x9570a)
                #12 0x00007138ceb27aac n/a (libc.so.6 + 0x119aac)
                
                Stack trace of thread 167445:
                #0  0x00007138ceaabbe2 n/a (libc.so.6 + 0x9dbe2)
                #1  0x00007138cea9fe33 n/a (libc.so.6 + 0x91e33)
                #2  0x00007138ceaa04bc n/a (libc.so.6 + 0x924bc)
                #3  0x00007138ceaa2c0e pthread_cond_wait (libc.so.6 + 0x94c0e)
                #4  0x00007138b9b003ee n/a (libgallium-25.0.2-arch1.2.so + 0x5003ee)
                #5  0x00007138b9acaecc n/a (libgallium-25.0.2-arch1.2.so + 0x4caecc)
                #6  0x00007138b9b0031d n/a (libgallium-25.0.2-arch1.2.so + 0x50031d)
                #7  0x00007138ceaa370a n/a (libc.so.6 + 0x9570a)
                #8  0x00007138ceb27aac n/a (libc.so.6 + 0x119aac)
                
                Stack trace of thread 167443:
                #0  0x00007138ceaabbe2 n/a (libc.so.6 + 0x9dbe2)
                #1  0x00007138cea9fe33 n/a (libc.so.6 + 0x91e33)
                #2  0x00007138ceaa04bc n/a (libc.so.6 + 0x924bc)
                #3  0x00007138ceaa2c0e pthread_cond_wait (libc.so.6 + 0x94c0e)
                #4  0x00007138cf2e53b8 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x2e53b8)
                #5  0x00007138cadba56f n/a (libQt6WaylandClient.so.6 + 0x6056f)
                #6  0x00007138cf2d8a9b n/a (libQt6Core.so.6 + 0x2d8a9b)
                #7  0x00007138ceaa370a n/a (libc.so.6 + 0x9570a)
                #8  0x00007138ceb27aac n/a (libc.so.6 + 0x119aac)
                
                Stack trace of thread 167451:
                #0  0x00007138ceaabbe2 n/a (libc.so.6 + 0x9dbe2)
                #1  0x00007138cea9fe33 n/a (libc.so.6 + 0x91e33)
                #2  0x00007138cea9fe74 n/a (libc.so.6 + 0x91e74)
                #3  0x00007138ceb1aa06 ppoll (libc.so.6 + 0x10ca06)
                #4  0x00007138ce28de27 n/a (libglib-2.0.so.0 + 0xc1e27)
                #5  0x00007138ce229535 g_main_context_iteration (libglib-2.0.so.0 + 0x5d535)
                #6  0x00007138cf3c575d _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x3c575d)
                #7  0x00007138cf1606a6 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x1606a6)
                #8  0x00007138cf257999 _ZN7QThread3runEv (libQt6Core.so.6 + 0x257999)
                #9  0x00007138cf2d8a9b n/a (libQt6Core.so.6 + 0x2d8a9b)
                #10 0x00007138ceaa370a n/a (libc.so.6 + 0x9570a)
                #11 0x00007138ceb27aac n/a (libc.so.6 + 0x119aac)
                
                Stack trace of thread 167446:
                #0  0x00007138ceaabbe2 n/a (libc.so.6 + 0x9dbe2)
                #1  0x00007138cea9fe33 n/a (libc.so.6 + 0x91e33)
                #2  0x00007138ceaa04bc n/a (libc.so.6 + 0x924bc)
                #3  0x00007138ceaa2c0e pthread_cond_wait (libc.so.6 + 0x94c0e)
                #4  0x00007138b9b003ee n/a (libgallium-25.0.2-arch1.2.so + 0x5003ee)
                #5  0x00007138b9acaecc n/a (libgallium-25.0.2-arch1.2.so + 0x4caecc)
                #6  0x00007138b9b0031d n/a (libgallium-25.0.2-arch1.2.so + 0x50031d)
                #7  0x00007138ceaa370a n/a (libc.so.6 + 0x9570a)
                #8  0x00007138ceb27aac n/a (libc.so.6 + 0x119aac)
                
                Stack trace of thread 167444:
                #0  0x00007138ceaabbe2 n/a (libc.so.6 + 0x9dbe2)
                #1  0x00007138cea9fe33 n/a (libc.so.6 + 0x91e33)
                #2  0x00007138cea9fe74 n/a (libc.so.6 + 0x91e74)
                #3  0x00007138ceb1a53e __poll (libc.so.6 + 0x10c53e)
                #4  0x00007138cadba5d7 n/a (libQt6WaylandClient.so.6 + 0x605d7)
                #5  0x00007138cf2d8a9b n/a (libQt6Core.so.6 + 0x2d8a9b)
                #6  0x00007138ceaa370a n/a (libc.so.6 + 0x9570a)
                #7  0x00007138ceb27aac n/a (libc.so.6 + 0x119aac)
                ELF object binary architecture: AMD x86-64
```

**Comment by Mahdi-zarei** [comment]
This [Fix vc redist cmake](https://github.com/Mahdi-zarei/nekoray/commit/87304b74f9bdce6a29027ed145c30ffcf8e9b509) should fix it.

**Comment by Integral-Tech** [comment]
@Mahdi-zarei It doesn't work, SIGSEGV (Address boundary error) still appears.

**Comment by Mahdi-zarei** [comment]
I don't know how you define 'reverting a commit' but the crash has nothing to do with https://github.com/Mahdi-zarei/nekoray/commit/9f89e48733b651888192409e22afe3f921544c68, it was caused by https://github.com/Mahdi-zarei/nekoray/commit/fa06493aa90adabc46ca680e2831d2a484bd7152 and should be fixed now.
